### ISSUE TITLE
Getting Weird Translation

### ISSUE THREAD

**Issue by roo12312** [AidanWelch/google-translate-api#13]
Hi im not getting the same result when i translate in google translate and using google-translate-api.
What might be the issue?

**Comment by AidanWelch** [comment]
I don't know exactly what it is without seeing an example of the input, but it could be a couple things.  Notably, it could be autocorrect, or it could be that this API defaults to female gendered words, whereas the browser Google Translate shows male often.

**Comment by therealsamsquanch** [comment]
Perhaps is the same issue described here: https://github.com/Songkeys/Translateer/issues/2#issuecomment-1102488530

**Comment by AidanWelch** [comment]
> Perhaps is the same issue described here: [Songkeys/Translateer#2 (comment)](https://github.com/Songkeys/Translateer/issues/2#issuecomment-1102488530)

Could be but its hard to tell without an example of it happening, but it wouldn't be Puppeteer detection because this project isn't using Puppeteer but yeah another detection is possible.

**Comment by AidanWelch** [comment]
This might be fixed by using the single translate endpoint now supported

**Comment by AidanWelch** [comment]
Closed as stale
