### ISSUE TITLE
Real-time translation

### ISSUE THREAD

**Issue by vfa-locltb** [AidanWelch/google-translate-api#19]
Can this package translate in real-time, like users don't need to press the translate button to translate, but just need to type and wait for it to auto translate?

**Comment by AidanWelch** [comment]
You can implement that, just add a listener to the text element for change, or send a translation request every x number of seconds if the text is different.  I've found with this endpoint you're unlikely to be blocked.

**Comment by AidanWelch** [comment]
This seems stale, and is beyond the scope of this project
