### ISSUE TITLE
TypeScript Error

### ISSUE THREAD

**Issue by d1ksim** [AidanWelch/google-translate-api#21]
TS2339: Property 'text' does not exist on type 'ITranslateResponse | ITranslateResponse[] | { [x: string]: ITranslateResponse; }'.   Property 'text' does not exist on type 'ITranslateResponse[]'.

I use React and TypeScript.

`const translator = new Translator({from: 'en', to: 'es', forceBatch: false, tld: 'es'});
    const res = await translator.translate('Ik spreek Engels', {to: user_data!.lang});
    console.log(res.text)`

**Comment by AidanWelch** [comment]
Typescript definitions are outdated, I will try to update soon but have been busy

**Comment by AidanWelch** [comment]
Fixed in 5ddcc045e185c2c32c49f2fe353832a96efd8175
