### ISSUE TITLE
It throws error "fetch is not defined"

### ISSUE THREAD

**Issue by pekonchan** [AidanWelch/google-translate-api#23]
My demo is simple , just like this.
```
(async() => {
    const translate = require('google-translate-api-x');
    const res = await translate('Ik spreek Engels', {to: 'zh'});
    console.log(res.text);
})()
```
When run the code, it throws the error

![image](https://user-images.githubusercontent.com/38689834/212005338-9ab7f5de-9fe5-4442-8378-cdc36d0fc2be.png)

**Comment by AidanWelch** [comment]
@pekonchan If you are using a node version before v17.5(I believe you are) you must use [node-fetch](https://www.npmjs.com/package/node-fetch) as described in [#20](https://github.com/AidanWelch/google-translate-api/issues/20)

**Comment by pekonchan** [comment]
> @pekonchan If you are using a node version before v17.5(I believe you are) you must use [node-fetch](https://www.npmjs.com/package/node-fetch) as described in [#20](https://github.com/AidanWelch/google-translate-api/issues/20)

oh, I got it . Thank you
