### ISSUE TITLE
google-translate-api-x  gives below error

### ISSUE THREAD

**Issue by nkpatel0801** [AidanWelch/google-translate-api#26]
error: node_modules/google-translate-api-x/lib/Translator.cjs: /home/nirali/Desktop/farmerAssistantApp/node_modules/google-translate-api-x/lib/Translator.cjs: Class private methods are not enabled. Please add `@babel/plugin-proposal-private-methods` to your configuration.

**Comment by AidanWelch** [comment]
This project doesn't use babel.  That should be configured in the implementation-end.

**Comment by AidanWelch** [comment]
You should just be able to install it like this https://babeljs.io/docs/babel-preset-env

**Comment by kirandchavan** [comment]
we already have this in devDependencies
`"@babel/preset-env": "^7.20.0",`

can you please provide steps like what needs to be added or udated?

**Comment by AidanWelch** [comment]
Actually that started having more issues such as `require not defined` but 

babel.config.js
```js
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
	plugins: [["@babel/plugin-proposal-private-methods", { "loose": true }]],
  };
};
```

works fine
