### ISSUE TITLE
Batch translation error

### ISSUE THREAD

**Issue by eyelly-wu** [AidanWelch/google-translate-api#33]
Error Info
>  Partial Translation Request Fail: at least one translation failed, it was either invalid or more likely- rejected by the server.  You can try the request again and if it persists try a proxy, spacing out requests, and/or using a different tld.  If you would like to translate other requests in a batch translation even if one fails(the failed translation will be set to `null`) pass the option `rejectOnPartialFail: false`.  You can also try using the singleTranslate endpoint with: `forceBatch: false`

A reproducible example
https://runkit.com/eyelly/64787340c932b600084ae8ee

Thanks to the author for providing this tool library, hope this problem can be fixed

**Comment by AidanWelch** [comment]
This really is interesting behavior, and makes me wonder if Google has implemented some kind of automatic rejection of requests if they would take too long or something?  It seems relatively new, and mostly effects batch translates.  As you can see by passing `rejectOnPartialFail: false` generally at least one request fails, but the generally at least one succeeds- and it's not predictable which one will.  I'll investigate and see what I can find.

**Comment by AidanWelch** [comment]
Okay, it seems like investigating, I'm back to my old enemy of the `X-Goog-BatchExecute-Bgr` header is what determines if it fails or not largely.

**Comment by AidanWelch** [comment]
So, related to #18

**Comment by eyelly-wu** [comment]
Thank you once again, and I hope a solution can be found in the future.

**Comment by eyelly-wu** [comment]
Batch translation is already working fine, so I closed the issue

**Comment by AidanWelch** [comment]
That's good, but I don't like how sometimes the quality is bad.
