### ISSUE TITLE
fetch is not defined after deployment

### ISSUE THREAD

**Issue by MiracleUFO** [AidanWelch/google-translate-api#38]
@AidanWelch This package works fine when I start my server in terminal, but as soon as I deploy to Render it says `ERROR ReferenceError: fetch is not defined at Object.requestFunction (/opt/render/project/src/node_modules/google-translate-api-x/lib/defaults.cjs:9:36)`, seems it isn't truly cross-platform or is there something I could do different to get it to work in a pure Node environment?

All the help will be appreciated and the batching feature is truly an improvement on the [vitalets ](https://github.com/vitalets/google-translate-api) package. Thank you! ✨

**Comment by AidanWelch** [comment]
Older versions of Node don't fully implement the current ES6 standard such as `fetch`.  See the pinned issue #20 on using `node-fetch`.

Thank you!

**Comment by MiracleUFO** [comment]
> Older versions of Node don't fully implement the current ES6 standard such as `fetch`. See the pinned issue #20 on using `node-fetch`.
> 
> Thank you!

Thank you, this works!
