### ISSUE TITLE
CORS policy error 

### ISSUE THREAD

**Issue by DreamerKamyar** [AidanWelch/google-translate-api#39]
i installed your package and tried the description but unfortunately i get errors about CORS error, and i don't know how to solve it

**Comment by AidanWelch** [comment]
I'm sorry to hear that but am a little confused, if you know how to solve it what's the problem?

**Comment by DreamerKamyar** [comment]
sorry i made a mistake in writing about it 
Access to fetch at 'https://translate.google.com/_/TranslateWebserverUi/data/batchexecute?rpcids=MkEWBc&source-path=%2F&f.sid=&bl=&hl=en-US&soc-app=1&soc-platform=1&soc-device=1&_reqid=2982&rt=c' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. 

this is the error i got from it

**Comment by AidanWelch** [comment]
@DreamerKamyar 

Ah okay, unfortunately in some cases this is unavoidable.  [More information here.](https://github.com/AidanWelch/google-translate-api/issues/11)

But essentially, it is not possible to use this package in the front end of a website because of the Same Origin Policy.

**Comment by DreamerKamyar** [comment]
oh that was the reason I couldn't use it in front end. 
thank you so much.
