### ISSUE TITLE
improve type definitions

### ISSUE THREAD

**Issue by sglkc** [AidanWelch/google-translate-api#47]
Hi, thanks for the package. I always use this with TypeScript and there's this issue that's bugging me, perhaps for other TS developers too.

1. There are export functions that are not typed, it's an error, but still usable.
![image](https://github.com/user-attachments/assets/40123404-75b4-4904-a5fb-e76a86d626e6)
![image](https://github.com/user-attachments/assets/22b6b2c1-d06a-4073-bb25-81389747e2bd)

2. Types are scoped in googleTranslateApi and cannot be imported directly from package
![image](https://github.com/user-attachments/assets/174d381c-3e90-4a09-901b-af9f6938d889)

I can make a PR but it might break for older version

**Comment by AidanWelch** [comment]
Thanks for pointing out 1, I fixed it in [v10.7.1](https://github.com/AidanWelch/google-translate-api/releases/tag/v10.7.1), as for 2 I don't really think it is a major issue so I think it is best if it is not changed.

**Comment by sglkc** [comment]
Also I forgot another minor issue in documentation, the `raw` option doesn't exist.

[README.md#244](https://github.com/AidanWelch/google-translate-api/blob/2e9819d775b2de338b93ab80012fe582ba72cef9/README.md?plain=1#L244) [README.md#320](https://github.com/AidanWelch/google-translate-api/blob/2e9819d775b2de338b93ab80012fe582ba72cef9/README.md?plain=1#L320)

**Comment by AidanWelch** [comment]
Yeah, that's because the `raw` option doesn't do anything, and I have no clue when that changed somewhere in the version history.  I plan to at some point go through all the legacy documentation, but I'm fairly busy right now.

**Comment by sglkc** [comment]
Alrighty, thanks. I'll close the issue
